#version 450
layout(local_size_x =16, local_size_y =16, local_size_z =1) in;

layout(push_constant) uniform PushConstant {
    uint faceIndex;
    uint faceSize;
    float roughness;
    uint resolution;
} pc;

layout(set=0,binding=2) uniform samplerCube envTexture;
layout(set=0, binding=3, rgba16f) uniform writeonly image2D cubeFace;

const float PI = 3.14159265358979323846;

vec3 getNormalDirection(vec2 uv, uint faceIndex) {
    vec2 local = uv * 2.0 -1.0;

    vec3 dir;

    switch(faceIndex) {
        case 0:
        dir = vec3(1.0, -local.y, -local.x);
        break;
        case 1:
        dir = vec3(-1.0, -local.y, local.x);
        break;
        case 2:
        dir = vec3(local.x, 1.0, local.y);
        break;
        case 3:
        dir = vec3(local.x, -1.0, -local.y);
        break;
        case 4:
        dir = vec3(local.x, -local.y, 1.0);
        break;
        default:
        dir = vec3(-local.x, -local.y, -1.0);
        break;
    }

    return normalize(dir);
}

mat3 generateTBNMatrix( vec3 N) {
vec3 up =
    abs(N.y) < 0.999
    ? vec3(0,1,0)
    : vec3(1,0,0);
vec3 right = normalize(cross(up, N));
up = normalize(cross(N,right));

return mat3(right,up,N);

}

float radicalInverse(uint bits) {
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10;
}

vec2 hammersley(uint i, uint N) {
    return vec2(float(i) / float(N), radicalInverse(i));
}


vec3 ImportanceSampleGGX( float roughness, vec2 Xi, mat3 TBN) {

 float a = roughness*roughness;
    float phi = 2.0 * PI * Xi.x;

  float cosTheta =
sqrt(
    (1.0 - Xi.y) /
    (1.0 + (a*a - 1.0) * Xi.y)
); 

float sinTheta = sqrt( 1.0 - cosTheta*cosTheta);

vec3 H;

H.x = sinTheta * cos(phi);
H.y = sinTheta * sin(phi);
H.z  = cosTheta;

H = normalize(TBN * H);

return H;

}
float DistributionGGX(float NdotH, float roughness)
{
    float a  = roughness * roughness;
    float a2 = a * a;

    float denom = NdotH * NdotH * (a2 - 1.0) + 1.0;

    return a2 / (PI * denom * denom);
}


void main() {
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

     if(pixelCoord.x >= int(pc.faceSize) || pixelCoord.y >= int(pc.faceSize)){
        return;
    }
     vec2 uv = vec2(pixelCoord + 0.5) /float(pc.faceSize);
     vec3 N = getNormalDirection(uv, pc.faceIndex);
     float roughness = pc.roughness;
      vec3 V = N;
      uint SAMPLES = 1024u;
      mat3 TBN = generateTBNMatrix(N);
    vec3 accumulation = vec3(0.0);

      float totalWeight = 0.0;

       for(uint i =0u;i  < SAMPLES; i++) { 
         vec2 Xi = hammersley(i, SAMPLES);
        vec3 H = ImportanceSampleGGX(roughness, Xi, TBN);
         vec3 L = normalize(reflect(-V, H));
     
         float NdotL = max(dot(N, L), 0.0);
      if (NdotL > 0.0)
{

    float NdotH = max(dot(N,H),0.0);
    float VdotH = NdotH;
    float D = DistributionGGX(NdotH, roughness);

    float pdf =(D * NdotH / (4.0 * VdotH)) + 0.0001;
    float saTexel = 4.0 * PI / (6.0 * pc.resolution * pc.resolution); 
    float saSample = 1.0 / (float(SAMPLES) * pdf + 0.0001);
    float maxMip = log2(float(pc.resolution)); 
    float mipLevel = roughness == 0.0 ? 0.0 : 
    0.5 * log2(saSample / saTexel);

    accumulation += textureLod(envTexture, L, clamp(mipLevel, 0.0, maxMip)).rgb * NdotL;
    totalWeight += NdotL;
}

       }  


if(totalWeight > 0.0) {
    accumulation /= totalWeight;
}
       imageStore(cubeFace, pixelCoord, vec4(accumulation, 1.0) );



}