#version 450
#define EMITTER_TYPE_CONTINUOUS 0u
#define EMITTER_TYPE_BURST 1u
layout(local_size_x=64) in;

struct EmitterDesc{
 vec4 position;
 vec4 direction;
 vec4 startColor;
 vec4 endColor;
 vec4 gravity;
 vec4 wind;
 vec4 spawnAreaExtent;
 float startSize;
 float endSize;
 float  spawnRate; 
 float initialSpeed;
 float speedVariance;
 float spread;
 float minLifetime;
 float maxLifetime;
 float spawnAccumulator;
 float drag;
 float burstCount;
 float hasFired;
 float swayAmplitude;
 float swayFrequency;
 uint type;
};

struct Particle {
       vec4 position;
       vec4 velocity;
        vec4 color;
        float lifetime;
        float age;
        float size;
        uint emitterId;
};

layout(std430,set=0, binding=2) buffer ParticleBuffer {
 Particle particles[];
};

layout(std430,set=0, binding=3) buffer DeadList {
    uint count;
    uint indices[];
} deadList;

layout(std430,set=0, binding=4) buffer EmitterBuffer {
 EmitterDesc emitters[];
};

layout(push_constant) uniform PushConstant {
 uint emitterCount;
 uint frameIndex;
 uint maxParticles;
 float frameTime;
};

uint hash(uint seed) {
    seed ^= seed >> 16;
    seed *= 0x45d9f3b;
    seed ^= seed >> 16;
    return seed;
}

const float PI = 3.14159265358979323846;

float rand(uint seed) 
{ 
    return float(hash(seed)) / 4294967295.0; 
}

vec3 generateRandomSpreadDirection(float spread, uint seed) {

float cosTheta = mix(1.0, cos(spread), rand(seed));
float sinTheta =sqrt( 1.0 - (cosTheta * cosTheta));

float phi = 2 * PI * rand(seed + 1u);

return vec3(
    sinTheta * cos(phi),
    sinTheta * sin(phi),
    cosTheta
);
}

mat3 generateParticleBasisVector(vec3 dir) {
    vec3 up =abs(dir.y) > 0.99 ? vec3(0,0,1) : vec3(0,1,0);
    vec3 right = normalize(cross(up, dir));
    up = normalize(cross(dir, right));

    return mat3(right, up, dir); 
}

vec3 generateParticleDirection(vec3 dir,float spread, uint seed) {
  vec3 spreadDir = generateRandomSpreadDirection(spread, seed);
   mat3 basisVectors = generateParticleBasisVector(normalize(dir));

   return basisVectors * spreadDir;

}

void main() {
    uint id = gl_GlobalInvocationID.x;

    if(id >= emitterCount) return;
       
    EmitterDesc emitter = emitters[id];
    
    emitter.spawnAccumulator += float(emitter.spawnRate) * frameTime;
    uint numParticles = uint(emitter.spawnAccumulator);
    emitter.spawnAccumulator -= float(numParticles);
     
 if(emitter.type == EMITTER_TYPE_BURST) {
    if(emitter.burstCount > 0.0 && emitter.hasFired < 0.5f) {
      for(uint i=0; i < emitter.burstCount; i++) {

     uint oldCount, newCount;

     do {
        oldCount = deadList.count;
        if(oldCount == 0u) break;
        newCount = oldCount -1;
     } while(atomicCompSwap(deadList.count, oldCount, newCount) != oldCount);

    uint deadIdx = oldCount - 1;
    if(deadIdx >= maxParticles) break;
     
      uint particleIdx = deadList.indices[deadIdx];
      
      uint seed = particleIdx * 1234567u + frameIndex;
     
      particles[particleIdx].lifetime = mix(emitter.minLifetime, emitter.maxLifetime, rand(seed));
      particles[particleIdx].age = 0.0;
      particles[particleIdx].size = 0.05;
      particles[particleIdx].color = mix(emitter.startColor, emitter.endColor, rand(seed));
     
     float r = rand(seed);
     
     float variation = mix(-emitter.speedVariance, emitter.speedVariance, r);

     float speed = emitter.initialSpeed + variation;
    
    vec3 randomDirection = generateParticleDirection(emitter.direction.xyz, emitter.spread, seed);

     particles[particleIdx].velocity =vec4( speed * randomDirection, 0.0);
     vec3 spawnOffset = vec3(
    (rand(seed + 2u) * 2.0 - 1.0) * emitter.spawnAreaExtent.x,
    0.0,
    (rand(seed + 3u) * 2.0 - 1.0) * emitter.spawnAreaExtent.z
);
particles[particleIdx].position = emitter.position + vec4(spawnOffset, 0.0);
     particles[particleIdx].emitterId = id;

    }
    }
     emitters[id].hasFired = 1.0f;
   } else {
     for(uint i=0; i < numParticles; i++) {

     uint oldCount, newCount;

     do {
        oldCount = deadList.count;
        if(oldCount == 0u) break;
        newCount = oldCount -1;
     } while(atomicCompSwap(deadList.count, oldCount, newCount) != oldCount);

    uint deadIdx = oldCount - 1;
    if(deadIdx >= maxParticles) break;
     
      uint particleIdx = deadList.indices[deadIdx];
      
      uint seed = particleIdx * 1234567u + frameIndex;
     
      particles[particleIdx].lifetime = mix(emitter.minLifetime, emitter.maxLifetime, rand(seed));
      particles[particleIdx].age = 0.0;
      particles[particleIdx].size = 0.05;
      particles[particleIdx].color = mix(emitter.startColor, emitter.endColor, rand(seed));
     
     float r = rand(seed);
     
     float variation = mix(-emitter.speedVariance, emitter.speedVariance, r);

     float speed = emitter.initialSpeed + variation;
    
    vec3 randomDirection = generateParticleDirection(emitter.direction.xyz, emitter.spread, seed);

     particles[particleIdx].velocity =vec4( speed * randomDirection, 0.0);
        vec3 spawnOffset = vec3(
    (rand(seed + 2u) * 2.0 - 1.0) * emitter.spawnAreaExtent.x,
    (rand(seed + 3u) * 2.0 - 1.0) * emitter.spawnAreaExtent.y,
    (rand(seed + 4u) * 2.0 - 1.0) * emitter.spawnAreaExtent.z
);
particles[particleIdx].position = emitter.position + vec4(spawnOffset, 0.0);
     particles[particleIdx].emitterId = id;
     
    


    };
   }

    emitters[id].spawnAccumulator = emitter.spawnAccumulator;
  
    
    
    
}