#version 450
layout(local_size_x=16, local_size_y=16) in;

layout(set=0, binding=2) uniform sampler2D depthTex;
layout(set=0, binding=3, r32f) uniform image2D hizTex;

layout(push_constant) uniform PushConstant {
    vec2 textureSize;
};

void main() {
      ivec2 dst = ivec2(gl_GlobalInvocationID.xy);

         ivec2 dstSize = ivec2(textureSize);
if (dst.x >= dstSize.x || dst.y >= dstSize.y) {
    return;
}
float depth = texelFetch(depthTex, dst, 0).r;
imageStore(hizTex, dst, vec4(depth));
}