#version 450
layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

layout(push_constant) uniform PushConstant {
    uint faceIndex;
    uint faceSize;
} pc;


layout(set=0,binding=2) uniform samplerCube envTexture;
layout(set=0, binding=3, rgba16f) uniform writeonly image2D cubeFace;

const float PI = 3.14159265358979323846;

vec3 getNormalDirection(vec2 uv, uint faceIndex) {
    vec2 local = uv * 2.0 -1.0;

    vec3 dir;

    switch(faceIndex) {
        case 0:
        dir = vec3(1.0, -local.y, -local.x);
        break;
        case 1:
        dir = vec3(-1.0, -local.y, local.x);
        break;
        case 2:
        dir = vec3(local.x, 1.0, local.y);
        break;
        case 3:
        dir = vec3(local.x, -1.0, -local.y);
        break;
        case 4:
        dir = vec3(local.x, -local.y, 1.0);
        break;
        default:
        dir = vec3(-local.x, -local.y, -1.0);
        break;
    }

    return normalize(dir);
}

mat3 generateTBNMatrix( vec3 N) {
vec3 up =
    abs(N.y) < 0.999
    ? vec3(0,1,0)
    : vec3(1,0,0);
vec3 right = normalize(cross(up, N));
up = normalize(cross(N,right));

return mat3(right,up,N);

}


float radicalInverse(uint bits) {
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10;
}

vec2 hammersley(uint i, uint N) {
    return vec2(float(i) / float(N), radicalInverse(i));
}

vec3 sampleIrradiance(mat3 TBN, vec3 normal, samplerCube environment) {
 vec3 irradiance = vec3(0.0);
 uint sampleCount =0u;
 float sampleDelta = 0.001;

 for(float theta =0; theta <= PI/2; theta+= sampleDelta){
    for(float phi =0.0; phi <= 2*PI; phi += sampleDelta) {
 vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta)* sin(phi), cos(theta));
 vec3 mainSample = TBN * tangentSample;

 irradiance += textureLod(environment, mainSample, 0.0).rgb * cos(theta) * sin(theta);
 sampleCount += 1u;
 }
 }

 return PI* irradiance / float(sampleCount);

// TODO:
// Replace brute-force hemisphere integration with
// Hammersley importance sampling.
// Current implementation is the correctness reference.

    // vec3  irradiance  = vec3(0.0);
    // uint  SAMPLE_COUNT = 72768u; 

    // for (uint i = 0u; i < SAMPLE_COUNT; i++) {
    //     vec2 xi = hammersley(i, SAMPLE_COUNT);

    //     // Map xi to spherical coordinates (cosine-weighted hemisphere)
    //     float phi      = 2.0 * PI * xi.x;
    //     float cosTheta = sqrt(1.0 - xi.y);  // cosine-weighted distribution
    //     float sinTheta = sqrt(xi.y);

    //     vec3 tangentSample = vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta);
    //     vec3 worldSample   = normalize(TBN * tangentSample);
    //     // vec3 worldSample   = normalize(TBN * vec3(0.0,0.0,1.0));

    //     irradiance += texture(environment, worldSample).rgb * cosTheta ;
    //     // irradiance += worldSample * 0.5 + 0.5;
    // }
    // return PI *  irradiance / float(SAMPLE_COUNT);

}


void main() {
   ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

   if(pixelCoord.x >= int(pc.faceSize) || pixelCoord.y >= int(pc.faceSize)) return;

   vec2 uv = vec2(pixelCoord + 0.5) /float(pc.faceSize);
   vec3 normal = getNormalDirection(uv, pc.faceIndex);
//    vec3 normal = vec3(0,0,1);
   mat3 TBN = generateTBNMatrix(normal);
   vec3 irradiance = sampleIrradiance(TBN, normal, envTexture);

vec3 color = texture(envTexture, normal).rgb;
   imageStore(cubeFace, pixelCoord,  
   
   vec4(irradiance,1)); 


}