#pragma once
#include "shadow-pass.h"
#include "main-pass.h"
#include "geometry-pass.h"
#include "cascade-shadow-map-pass.h"
#include "forward-lighting-pass.h"
#include "deferred-lighting-pass.h"
#include "depth-prepass.h"
#include "lighting-stencil-pass.h"