#version 450
layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

const float GAUSSIAN_WEIGHTS[5] = float[] (0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);

layout(push_constant) uniform PushConstant {
 vec2 inputTextureSize;
 vec2 outputTextureSize;
 uint horizontal;   
} pc;

layout(set=0, binding=2) uniform sampler2D srcTexture;
layout(set=0, binding=3, rgba16f) uniform writeonly image2D dstTexture;




void main() {
ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
if(float(pixelCoord.x ) >= pc.outputTextureSize.x || float(pixelCoord.y) >= pc.outputTextureSize.y) return;
vec2 uv = (vec2(pixelCoord) + 0.5) / pc.outputTextureSize;
vec2 texOffset = 1.0 / pc.inputTextureSize;
vec3 result =  texture(srcTexture, uv).rgb * GAUSSIAN_WEIGHTS[0];
for(int i =1; i < 5; i++) {
    float fi = float(i);
    vec2 offset = pc.horizontal == 1 ?  vec2(texOffset.x * fi,0.0) :vec2(0.0, texOffset.y * fi);
   result += texture(srcTexture, uv - offset).rgb * GAUSSIAN_WEIGHTS[i];
     result += texture(srcTexture, uv + offset).rgb * GAUSSIAN_WEIGHTS[i];
}

imageStore(dstTexture, pixelCoord, vec4(result,1.0));

}
