#version 450
layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

layout(push_constant) uniform PushConstant {
 vec2 inputTextureSize;
 vec2 outputTextureSize;
} pc;

layout(set =0, binding=2) uniform sampler2D hdrTexture;
layout(set=0, binding=3, rgba32f) uniform writeonly image2D outputTexture;



void main() {
 ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

 if(pixelCoord.x >= int(pc.outputTextureSize.x) || pixelCoord.y >= int(pc.outputTextureSize.y)) return;

 vec2 uv = (vec2(pixelCoord) + 0.5) / pc.outputTextureSize;
 vec3 color = texture(hdrTexture, uv).rgb;
 float luma = dot(color, vec3(0.2126, 0.7152, 0.0722));
 float epsilon = 1e-4;
 float logLuma = log(luma + epsilon);
 vec3 result = vec3(logLuma);

 imageStore(outputTexture, pixelCoord, vec4(result,1.0));
}