#version 450
layout(local_size_x=16,local_size_y=16, local_size_z=1) in;


layout(push_constant) uniform PushConstant {
 vec2 inputTextureSize;
 vec2 outputTextureSize;
} pc;


layout(set =0, binding=2) uniform sampler2D srcTexture;
layout(set=0, binding=3, rgba32f) uniform writeonly image2D dstTexture;

void main() {
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

 if(pixelCoord.x >= int(pc.outputTextureSize.x) || pixelCoord.y >= int(pc.outputTextureSize.y)) return;

 vec2 uv = (vec2(pixelCoord) + 0.5) / pc.outputTextureSize;
vec2 texOffset = 1.0 / pc.inputTextureSize;
ivec2 srcBase = pixelCoord * 2;
vec3 samples = vec3(0.0);
for (int y = 0; y < 2; y++) {
    for (int x = 0; x < 2; x++) {
        samples += texelFetch(srcTexture, srcBase + ivec2(x, y), 0).rgb;
    }
}
vec3 result = samples / 4.0;

imageStore(dstTexture, pixelCoord, vec4(result,1.0));

}